[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/", "@ccip/=lib/ccip/", "@chainlink-local/=lib/chainlink-local/"]
rpc_endpoints = { sepolia-eth = "https://sepolia.infura.io/v3/ef140c0f20934c5f8f8c30838c57befa", arb-sepolia = "https://arbitrum-sepolia.infura.io/v3/ef140c0f20934c5f8f8c30838c57befa" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
